blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Article:index }

article_detail:
    path: /article/{id}
    defaults: { _controller: BlogBundle:Article:detail }
    requirements:
        id: \d+

category_list:
    path: /category/{id}
    defaults: { _controller: BlogBundle:Category:list }

article_create:
    path: /article/create
    defaults: { _controller: BlogBundle:Article:create }

article_delete:
    path: /article/{id}/delete
    defaults: { _controller: BlogBundle:Article:delete }
    methods: [POST]
    requirements:
        id: \d+
