services:
#    blog.example:
#        class: BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
# Fixtures services
    BlogBundle\DataFixtures\ORM\Fixtures:
        tags: [doctrine.fixture.orm]

    BlogBundle\Controller\RestController:
        arguments: ["@service_container", "@fos_rest.view_handler.default"]
        public: true
