BlogBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            nullable: true
        lastName:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: false
        content:
            type: text
            nullable: false
        createdAt:
            type: datetime
            nullable: true
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue]
