BlogBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            nullable: true
        lastName:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        password:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
